# - Try to find Assimp
# Once done, this will define
#
# ASSIMP_FOUND - system has Assimp
# ASSIMP_INCLUDE_DIR - the Assimp include directories
# ASSIMP_LIBRARIES_DEBUG - link these to use Assimp Debug
# ASSIMP_LIBRARIES - link these to use Assimp Release
FIND_PATH(ASSIMP_INCLUDE_DIR assimp/mesh.h
	${CMAKE_SOURCE_DIR}/includes
)

FIND_LIBRARY(ASSIMP_LIBRARY_DEBUG
	NAMES assimp-vc143-mtd.lib
        assimp-vc142-mtd.lib
        assimp-vc141-mtd.lib
	PATHS ${CMAKE_SOURCE_DIR}/lib
)

FIND_LIBRARY(ZLIB_LIBRARY_DEBUG
	NAMES zlibstaticd.lib
	PATHS ${CMAKE_SOURCE_DIR}/lib
)

FIND_LIBRARY(ASSIMP_LIBRARY
	NAMES assimp-vc143-mt.lib
        assimp-vc142-mt.lib
        assimp-vc141-mt.lib
	PATHS ${CMAKE_SOURCE_DIR}/lib
)

FIND_LIBRARY(ZLIB_LIBRARY
	NAMES zlibstatic.lib
	PATHS ${CMAKE_SOURCE_DIR}/lib
)

IF(ASSIMP_INCLUDE_DIR AND ASSIMP_LIBRARY_DEBUG AND ZLIB_LIBRARY_DEBUG)
	SET( ASSIMP_FOUND_DEBUG TRUE )
	SET( ASSIMP_LIBRARIES_DEBUG ${ASSIMP_LIBRARY_DEBUG} ${ZLIB_LIBRARY_DEBUG} )
ENDIF()

IF(ASSIMP_INCLUDE_DIR AND ASSIMP_LIBRARY AND ZLIB_LIBRARY)
	SET( ASSIMP_FOUND TRUE )
	SET( ASSIMP_LIBRARIES ${ASSIMP_LIBRARY} ${ZLIB_LIBRARY} )
ENDIF()

IF(ASSIMP_FOUND)
	IF(NOT ASSIMP_FIND_QUIETLY)
	MESSAGE(STATUS "Found ASSIMP: ${ASSIMP_LIBRARY}")
	ENDIF(NOT ASSIMP_FIND_QUIETLY)
ELSE()
	IF(ASSIMP_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find libASSIMP")
	ENDIF(ASSIMP_FIND_REQUIRED)
ENDIF()

IF(ASSIMP_FOUND_DEBUG)
	IF(NOT ASSIMP_FIND_QUIETLY)
	MESSAGE(STATUS "Found ASSIMP Debug: ${ASSIMP_LIBRARY_DEBUG}")
	ENDIF(NOT ASSIMP_FIND_QUIETLY)
ELSE()
	IF(ASSIMP_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find libASSIMP Debug")
	ENDIF(ASSIMP_FIND_REQUIRED)
ENDIF()